# Generated by Django 5.2.1 on 2025-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaReservasCompletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reservation_status', models.CharField(max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(max_length=20, null=True)),
                ('receipt_number', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'vista_reservas_completas',
                'managed': False,
            },
        ),
    ]
